name: validate
on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, reopened, synchronize, ready_for_review]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure pull-request addresses versioning
        uses: jefflinse/pr-semver-bump@v1.3.3
        with:
          mode: validate
          repo-token: ${{secrets.GITHUB_TOKEN}}
          release-notes-prefix: '^### Release Notes'
          release-notes-suffix: '^#{1,3}[^#]'
          require-release-notes: true
          with-v: true
